version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: dbdesc-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
      - ./data:/app/data
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: dbdesc-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped

  mcp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dbdesc-mcp
    depends_on:
      - backend
    # Uncomment below if you add HTTP transport to MCP server
    ports:
      - "8088:8088"
    restart: unless-stopped

